# Generated by Django 3.2.4 on 2021-07-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210706_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rate',
            field=models.IntegerField(blank=True, choices=[(1, 'Horrible'), (2, 'Bad'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True),
        ),
    ]
