# Generated by Django 3.2.4 on 2021-07-11 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210711_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Whis Lsit', 'verbose_name_plural': 'Wish Lists'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-added'], 'verbose_name': 'Wish List Item', 'verbose_name_plural': 'Wish lists Items'},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='added',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
