# Generated by Django 3.2.4 on 2021-07-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210712_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
