# Generated by Django 3.2.4 on 2021-07-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_wishlist_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-date_added'], 'verbose_name': 'Wish List', 'verbose_name_plural': 'Wishes Lists'},
        ),
    ]
